### PR TITLE
fix(lxc): allow container creation/update with correct mountoptions

### LINKED ISSUE #2315: container disk mount_options break the root disk by pointing to vm images
**Describe the bug**
Setting the mount_options of the disk of a  `proxmox_virtual_environment_container` does result in a broken container config.

**To Reproduce**

1. Create a resource 'and set the disk {mount_options = ["lazyatime"]}'
2. Run 'tofu apply' to create the resource
3. the plan that creates the container should look something like this: 

Image

4. check the created disk in the proxmox ui: 

Image

The mount option is missing. Also, learn that the storage path is: `storage:subvol-109xxxxx`
5. Run 'tofu apply' again and see that the missing option should be added: 

Image

6. check the proxmox gui and see that the storage path is like that of a VM: 

Image

`storage:vm-109-disk-0`

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl
resource "proxmox_virtual_environment_container" "lxc" {
  node_name = var.node_name

  vm_id = var.vm_id

  initialization {
    hostname = var.hostname

    ip_config {
      ipv4 {
        address = var.ipv4.address
        gateway = var.ipv4.gateway
      }
    }
    user_account {
      keys     = [var.authorized_keys]
      password = var.container_pw
    }
  }

  operating_system {
    template_file_id = var.template_file_id
    type             = "debian"
  }

  cpu {
    cores = var.cpu.cores
  }

  memory {
    dedicated = var.memory.dedicated
    swap      = var.memory.swap
  }

  startup {
    down_delay = 0
    order      = var.startup.order
    up_delay   = 0
  }

  started = true

  tags = var.tags

  disk {
    datastore_id  = var.disk.datastore_id
    size          = var.disk.size
    mount_options = var.disk.mount_options
  }

  network_interface {
    name        = var.network_interface.name
    bridge      = var.network_interface.bridge
    mac_address = var.network_interface.mac_address
  }


  features {
    nesting = true
  }

  timeout_create = 600
  timeout_delete = 600
  timeout_update = 600

  # add ansible user for ansible configuration management
  provisioner "local-exec" {
    command = "sleep 1; pushd ../../..; ansible-playbook playbook_provision_ansible_user.yml -e \"nodes=${self.initialization[0].hostname}\" --diff"
  }
}
```

the vars can be hardcoded to check the issue.

and the output of `terraform|tofu apply`.
```text
I can provide the output if required, but I have to redact alot because of the ansible prints
```

**Expected behavior**
the mount options should work on the first apply and the image should change completely on the second run.

**Additional context**
-

- Single or clustered Proxmox: single
- Proxmox version: 9.0.11
- Provider version (ideally it should be the latest version): 0.85.1
- Terraform/OpenTofu version: Opentofu 1.9.0
- OS (where you run Terraform/OpenTofu from): gentoo
- Debug logs (`TF_LOG=DEBUG terraform apply`): the important call looks like: `2025-11-04T01:15:40.526+0100 [DEBUG] provider.terraform-provider-proxmox_v0.85.1: Received HTTP Response: Cache-Control=max-age=0 Connection=Keep-Alive Date="Tue, 04 Nov 2025 00:15:40 GMT" Pragma=no-cache tf_http_res_status_code=200 tf_req_id=b6897722-fb98-215a-7775-c8db53ec0a95 tf_rpc=ApplyResourceChange Content-Type=application/json;charset=UTF-8 Server=pve-api-daemon/3.0 tf_http_res_status_reason="200 OK" tf_http_res_version=HTTP/1.1 tf_http_trans_id=09db037f-955a-7d9a-7ee1-3ad872006aa7 tf_mux_provider=tf5to6server.v5tov6Server tf_provider_addr=registry.terraform.io/bpg/proxmox @module=proxmox Content-Length=539 Expires="Tue, 04 Nov 2025 00:15:40 GMT" tf_http_op_type=response tf_http_res_body="{\"data\":{\"startup\":\"down=0,order=120,up=0\",\"console\":1,\"swap\":512,\"net0\":\"name=eth0,bridge=vmbr0,gw=192.168.2.1,hwaddr=ae:00:a7:21:f5:d6,ip=192.168.2.25/24,type=veth\",\"protection\":0,\"arch\":\"amd64\",\"cpuunits\":1024,\"tty\":2,\"cmode\":\"tty\",\"tags\":\"ehd;nginx_webserver\",\"onboot\":1,\"cores\":2,\"ostype\":\"debian\",\"hostname\":\"website-beta-ehd\",\"rootfs\":\"acl=0,size=4294967296,mountoptions=lazytime,quota=0,replicate=0,volume=storage:vm-109-disk-0\",\"memory\":512,\"features\":\"nesting=1\",\"digest\":\"289542f193b50341adfa71a7856015d5a0946cfe\",\"template\":0}}" tf_resource_type=proxmox_virtual_environment_container @caller=/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.38.1/helper/logging/logging_http_transport.go:162 timestamp="2025-11-04T01:15:40.526+0100"`

### PR DESCRIPTION
**Pull request by lexxxel**
Correct container mountoptions during creation and update.

### Contributor's Note

- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [x] I have added / updated acceptance tests in `/fwprovider/tests` for any new or updated resources / data sources.
- [x] I have ran `make example` to verify that the change works as expected.

### Proof of Work

```terraform
resource "proxmox_virtual_environment_container" "example_container" {
  node_name = "proxmox-01"
  vm_id     = 2345
  provider  = proxmox.proxmox-01

  initialization {
    hostname = "test-with-options"
  }

  operating_system {
    template_file_id = "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
    type             = "debian"
  }

  disk {
    datastore_id  = "storage"
    size          = 2
    mount_options = ["lazytime"] # <--- we change this line through out the PoW
  }

  timeout_create = 600
  timeout_delete = 600
  timeout_update = 600
}
``` 

`$ tofu apply` then outputs:  

```log
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

OpenTofu will perform the following actions:

  # proxmox_virtual_environment_container.example_container will be created
  + resource "proxmox_virtual_environment_container" "example_container" {
      + id             = (known after apply)
      + ipv4           = (known after apply)
      + ipv6           = (known after apply)
      + node_name      = "proxmox-01"
      + protection     = false
      + start_on_boot  = true
      + started        = true
      + template       = false
      + timeout_clone  = 1800
      + timeout_create = 600
      + timeout_delete = 600
      + timeout_start  = 300
      + timeout_update = 600
      + unprivileged   = false
      + vm_id          = 2345

      + disk {
          + acl           = false
          + datastore_id  = "storage"
          + mount_options = [
              + "lazytime",
            ]
          + quota         = false
          + replicate     = false
          + size          = 2
        }

      + initialization {
          + hostname = "test-with-options"
        }

      + operating_system {
          + template_file_id = "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
          + type             = "debian"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
proxmox_virtual_environment_container.example_container: Creating...
proxmox_virtual_environment_container.example_container: Still creating... [10s elapsed]
proxmox_virtual_environment_container.example_container: Still creating... [20s elapsed]
proxmox_virtual_environment_container.example_container: Creation complete after 24s [id=2345]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
``` 

image  

Now let's switch the `mount options` to `discard`:  

```terraform
  ...
  disk {
    datastore_id  = "storage"
    size          = 2
    mount_options = ["discard"] # <---
  }
  ...
```

```log
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

OpenTofu will perform the following actions:

  # proxmox_virtual_environment_container.example_container will be updated in-place
  ~ resource "proxmox_virtual_environment_container" "example_container" {
        id             = "2345"
        tags           = []
        # (14 unchanged attributes hidden)

      ~ disk {
          ~ mount_options = [
              - "lazytime",
              + "discard",
            ]
            # (5 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
proxmox_virtual_environment_container.example_container: Modifying... [id=2345]
proxmox_virtual_environment_container.example_container: Modifications complete after 0s [id=2345]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

image  

We do see that multiple things changed in the Proxmox UI, terraform does now apply all defaults when updating the mount point aka Root Disk and the size has changed from 2 Gigabyte to the byte equivalent. There is no resize happening at this point, it's just a different representation. This behavior was already in the provider and would look the same way, when changing other attributes, like the `acl`.  

Now to the relevant part: we can see, that the mount option has changed the way we wanted, and the container has been rebooted to apply the change (pls ignore the backup job, that is an unrelated cron job).  
  
Now let's activate `discard` and `lazytime` at the same time:  

```terraform
  ...
  disk {
    datastore_id  = "storage"
    size          = 2
    mount_options = ["discard", "lazytime"] # <---
  }
  ...
```

```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

OpenTofu will perform the following actions:

  # proxmox_virtual_environment_container.example_container will be updated in-place
  ~ resource "proxmox_virtual_environment_container" "example_container" {
        id             = "2345"
        tags           = []
        # (14 unchanged attributes hidden)

      ~ disk {
          ~ mount_options = [
                "discard",
              + "lazytime",
            ]
            # (5 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
proxmox_virtual_environment_container.example_container: Modifying... [id=2345]
proxmox_virtual_environment_container.example_container: Modifications complete after 0s [id=2345]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

image

Now both mount options are applied, and the container is restarted, again.

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #2315

### CODE REVIEW

**Comment by lexxxel** [comment]
The containerUpdate is still broken because of the hardcoded string in `getContainerDiskVolume`. Will tackle this next.

File: proxmoxtf/resource/container/container.go [hunk 1]
```diff
@@ -2985,11 +2985,15 @@ func containerUpdate(ctx context.Context, d *schema.ResourceData, m interface{})
...
-		rootFS.Volume = diskBlock[mkDiskDatastoreID].(string)
-		rootFS.Volume = getContainerDiskVolume(rootFS.Volume, vmID, diskID)
+		containerConfig, e := containerAPI.GetContainer(ctx)
+		if e != nil {
+			if errors.Is(e, api.ErrResourceDoesNotExist) {
+				d.SetId("")
+				return nil
+			}
+			return diag.FromErr(e)
+		}
```
Comment (lexxxel) [inline proxmoxtf/resource/container/container.go:2986]: Please tell me if this makes sense here.

Comment (bpg-dev) [reply proxmoxtf/resource/container/container.go:2986]: Hmmmm... what was the reason for adding this block? What problem are you trying to solve by this?
The behaviour seems questionable to me. If container doesn't exists on remote, and you're trying to _update_ it, this should be rather an error IMO.

Comment (lexxxel) [reply proxmoxtf/resource/container/container.go:2986]: I copied the whole block from somewhere else, where the get container(ctx) call was made this way. I did not understand the setid  call, that's why I raised the question. I do believe that it does not make sense and line 2988 is the only relevant one. Should I delete the rest?

**Comment by bpg-dev** [comment]
@all-contributors please add @lexxxel for code

File: proxmoxtf/resource/container/container.go (hunk 1 above)
Comment (bpg-dev) [reply proxmoxtf/resource/container/container.go:2986]: Yeah, we don't need that. I've updated the code and added an acceptance test, which passes. Would you mind also providing a 'Proof of Work' for the PR?
After that it will be good to go!

Comment (lexxxel) [reply proxmoxtf/resource/container/container.go:2986]: Yes, of course. How would you like to have that? As video or logs and screenshots?

Comment (bpg-dev) [reply proxmoxtf/resource/container/container.go:2986]: ty! just a log / screenshot, doesn't need to be super detailed, a small proof that the change fixes the problem.

Comment (lexxxel) [reply proxmoxtf/resource/container/container.go:2986]: Will do that tonight (in about 9h)

Comment (lexxxel) [reply proxmoxtf/resource/container/container.go:2986]: I modified the PR, is that good enough?

Comment (bpg-dev) [reply proxmoxtf/resource/container/container.go:2986]: Awesome, it's very detailed, thanks a lot!

**Review by bpg — APPROVED** [review]
Awesome work @lexxxel! 💪🏼 ❤️ 

LGTM! 🚀
