### PR TITLE
fix(sdn): correct evpn resource handling and improvements to base zone

### LINKED ISSUE #2500: SDN EVPN zone resource is crashing during apply on update
**Describe the bug**
SDN EVPN zone resource is crashing during apply on update.

**To Reproduce**

1. Create a resource proxmox_virtual_environment_sdn_zone_evpn
2. Run apply
3. See success
4. Modify the resource proxmox_virtual_environment_sdn_zone_evpn
5. Run apply
6. See error

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl

resource "proxmox_virtual_environment_sdn_zone_evpn" "crosssite" {
  id         = "crossite"
  controller = "evpnctl"
  vrf_vxlan  = 99999
  mtu        = 1370

  advertise_subnets          = true
  disable_arp_nd_suppression = false

  exit_nodes               = [local.proxmox_dell_r740_node_name]
  exit_nodes_local_routing = false
  ipam                     = "pve"

  depends_on = [
    proxmox_virtual_environment_sdn_applier.evpn_finalizer
  ]
}

resource "proxmox_virtual_environment_sdn_applier" "evpn_applier" {
  lifecycle {
    replace_triggered_by = [
      proxmox_virtual_environment_sdn_zone_evpn.crosssite,
    ]
  }

  depends_on = [
    proxmox_virtual_environment_sdn_zone_evpn.crosssite,
  ]
}

resource "proxmox_virtual_environment_sdn_applier" "finalizer" {}

```

and the output of `terraform|tofu apply`.
```text

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to proxmox_virtual_environment_sdn_zone_evpn.crosssite, provider
│ "provider[\"registry.opentofu.org/bpg/proxmox\"]" produced an unexpected new value:
│ .exit_nodes: planned set element cty.StringVal("proxmox-dell-r740") does not correlate with
│ any element in actual.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to proxmox_virtual_environment_sdn_zone_evpn.crosssite, provider
│ "provider[\"registry.opentofu.org/bpg/proxmox\"]" produced an unexpected new value:
│ .advertise_subnets: was cty.True, but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to proxmox_virtual_environment_sdn_zone_evpn.crosssite, provider
│ "provider[\"registry.opentofu.org/bpg/proxmox\"]" produced an unexpected new value:
│ .vrf_vxlan: was cty.NumberIntVal(99999), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to proxmox_virtual_environment_sdn_zone_evpn.crosssite, provider
│ "provider[\"registry.opentofu.org/bpg/proxmox\"]" produced an unexpected new value:
│ .controller: was cty.StringVal("evpnctl"), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to proxmox_virtual_environment_sdn_zone_evpn.crosssite, provider
│ "provider[\"registry.opentofu.org/bpg/proxmox\"]" produced an unexpected new value:
│ .exit_nodes_local_routing: was cty.True, but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Expected behavior**
Shoud be updates

**Screenshots**

**Additional context**

- Single or clustered Proxmox: Single
- Proxmox version: 9.1
- Provider version (ideally it should be the latest version): latest (0.93.0)
- Terraform/OpenTofu version: OpenTofu v1.11.2
- OS (where you run Terraform/OpenTofu from): linux
- Debug logs (`TF_LOG=DEBUG terraform apply`):

### PR DESCRIPTION
**Pull request by rafsaf**
### Contributor's Note

- [x] I have run `make lint` and fixed any issues.
- [x] I have updated documentation (FWK: schema descriptions + `make docs`; SDK: manual `/docs/` edits).
- [x] I have added / updated acceptance tests for any new or updated resources / data sources.
- [ ] I have run `make example` to verify the change works (mainly for SDK / provider config changes).

### Proof of Work
As in linked new issue #2500, evpn zone currently suffer from quite a few issues that are resolved in this PR. Some of changes contaminated into generic zone resource and other helper functions and zones. What seemed to be easy to fix, turned out to be nightmare to debug due to "pending" zone block that send int64, bool and strings as "deleted".

eg.:
```json
{
    "data": [
        {
            "state": "changed",
            "mac": "BC:24:11:D5:D3:EE",
            "ipam": "pve",
            "advertise-subnets": 1,
            "exitnodes": "pve",
            "exitnodes-local-routing": 1,
            "vrf-vxlan": 77,
            "pending": {
                "exitnodes": "deleted",
                "exitnodes-local-routing": "deleted",
                "advertise-subnets": "deleted"
            },
            "zone": "iiii",
            "digest": null,
            "type": "evpn",
            "controller": "evpnctl"
        }
    ]
}
```
- Strings were already handled properly ("deleted")
- Bool attributes like `exit_nodes_local_routing` are now computed and by default false. "deleted" from response correctly will handle it as `false` but then, if there is no default, we get "null" OR false from API depending if pending or not, this seems to be the only stable solution for all params
- Int64 - I was unable to fix MTU param, "deleted" from API will just result in crash and I think changes to make it work are unworth the effort. I believe `int64planmodifier.UseNonNullStateForUnknown` and proper docs are better than crash, that is **always going to happen** when you currently delete MTU field for any zone.
- stringset.ResourceAttribute - explicite "deleted" handling to mark it as empty set was needed, special handling in `CheckDelete` to treat planned `[]` as null and delete it in API
- move `checkDeletedFields` into zoneModel interface - this way zones like EVPN can add additional attributes to delete field, without it, those were never deleted  

### Acceptance tests

Since there is no evpn "controller" resource yet, there are no tests and they cannot be really written. I just created in in GUI and run added test with others. But i left the file without "acceptance" tag - will not run for the moment, but after there is controller, it can be added.

PS. SDN tests seem to be flaky sometimes (due to near infinite number of sdn apply probably), but that is also the case for main branch, at least on my virtual PVE setup.

```
$ ./testacc "TestAccResourceSDN*"
Running tests matching pattern: TestAccResourceSDN*
Searching all packages for pattern match
Package: github.com/bpg/terraform-provider-proxmox/fwprovider/...

ok      github.com/bpg/terraform-provider-proxmox/fwprovider    0.017s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/access     0.013s [no tests to run]
?       github.com/bpg/terraform-provider-proxmox/fwprovider/attribute  [no test files]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/acme       0.014s [no tests to run]
?       github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/ha [no test files]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/hardwaremapping    0.023s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/metrics    0.020s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/options    0.014s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/applier        51.143s
?       github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/fabric [no test files]
?       github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/fabric_node    [no test files]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/subnet 138.342s
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/vnet   14.179s
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/zone   30.779s
?       github.com/bpg/terraform-provider-proxmox/fwprovider/config     [no test files]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/nodes      0.065s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/apt  0.076s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/clonedvm     0.059s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/datastores   0.105s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/network      0.036s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/vm   0.033s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/vm/cdrom     0.027s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/vm/cpu       0.023s [no tests to run]
?       github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/vm/memory    [no test files]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/vm/rng       0.031s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/vm/vga       0.029s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/pools      0.025s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/storage    0.014s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/test       29.866s
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/types      0.011s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/types/hardwaremapping      0.015s [no tests to run]
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/types/nodes/apt    0.008s [no tests to run]
?       github.com/bpg/terraform-provider-proxmox/fwprovider/types/stringset    [no test files]
?       github.com/bpg/terraform-provider-proxmox/fwprovider/validators [no test files]
```

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #2500

### CODE REVIEW

File: fwprovider/cluster/sdn/zone/resource_qinq.go [hunk 1]
```diff
@@ -103,3 +103,8 @@ func (r *QinQResource) Schema(_ context.Context, _ resource.SchemaRequest, resp
 func (m *qinqModel) getGenericModel() *genericModel {
 	return &m.genericModel
 }
+
+func (m *qinqModel) checkDeletedFields(state zoneModel) []string {
+	qinqState := state.(*qinqModel)
+	return m.genericModel.checkDeletedFields(&qinqState.genericModel)
+}
```
[the remark this answers is not in the document]
Comment (rafsaf) [reply fwprovider/cluster/sdn/zone/resource_qinq.go:115]: added `Default:  stringdefault.StaticString("802.1q")` - after double check, this is enum in PVE API with default "802.1q", no delete is supported.

File: fwprovider/cluster/sdn/zone/resource_simple.go [hunk 2]
```diff
@@ -86,3 +86,8 @@ func (r *SimpleResource) Schema(_ context.Context, _ resource.SchemaRequest, res
 func (m *simpleModel) getGenericModel() *genericModel {
 	return &m.genericModel
 }
+
+func (m *simpleModel) checkDeletedFields(state zoneModel) []string {
+	simpleState := state.(*simpleModel)
+	return m.genericModel.checkDeletedFields(&simpleState.genericModel)
+}
```
[the remark this answers is not in the document]
Comment (rafsaf) [reply fwprovider/cluster/sdn/zone/resource_simple.go:98]: agree, fixed in last commit

File: fwprovider/cluster/sdn/zone/resource_simple.go [hunk 3]
```diff
@@ -86,3 +87,12 @@ func (r *SimpleResource) Schema(_ context.Context, _ resource.SchemaRequest, res
...
 	return &m.genericModel
 }
+
+func (m *simpleModel) checkDeletedFields(state zoneModel) []string {
+	simpleState := state.(*simpleModel)
+	toDelete := m.genericModel.checkDeletedFields(&simpleState.genericModel)
+
+	attribute.CheckDelete(m.DHCP, simpleState.DHCP, &toDelete, "dhcp")
+
+	return m.genericModel.checkDeletedFields(&simpleState.genericModel)
```
Comment (bpg-dev) [inline fwprovider/cluster/sdn/zone/resource_simple.go]: perhaps should just return `toDelete`?

**Review by bpg — CHANGES_REQUESTED** [review]
Thanks for the fix @rafsaf!

The changes make sense, have a one minor comment.

File: fwprovider/cluster/sdn/zone/resource_simple.go (hunk 3 above)
Comment (rafsaf) [reply fwprovider/cluster/sdn/zone/resource_simple.go]: that is correct, same fix in vxlan resource, fixed and rerun acc tests

ok      github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/subnet 129.381s
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/vnet   13.791s
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/zone   29.766s

Comment (bpg-dev) [reply fwprovider/cluster/sdn/zone/resource_simple.go]: thanks! that's a bit weird that we have state.genericModel and state.getGenericModel() there. need to clean up, but that's a different story.

**Comment by rafsaf** [comment]
> Great work as usual

Hold on :laughing:  We will see on that..., but I will try those fixes on my infra asap and get back if something is still missing here.
