### PR TITLE
fix(vm): prevent state changes after VM import

### LINKED ISSUE #932: Useless VM reboot during apply after importing
**Describe the bug**
When migrating from telmate proxmox provider to bpg provider, after import VM, a terraform apply reboot the VM whereas this is not mandatory/necessary

**To Reproduce**

1. Create a VM using telmate provider
2. remove this VM from state using `terraform state rm 'module.vm-test.proxmox_vm_qemu.proxmox-default[0]'`
3. import this VM: `terraform import 'module.vm-test.proxmox_virtual_environment_vm.proxmox-default[0]' proxmox09/109`
4. terraform apply

```
  # module.vm-test.proxmox_virtual_environment_vm.proxmox-default[0] will be updated in-place
  ~ resource "proxmox_virtual_environment_vm" "proxmox-default" {
        id                      = "109"
      + keyboard_layout         = "en-us"
      + migrate                 = false
        name                    = "ywh-dev-test-bgpprovider-node00"
      + on_boot                 = true
      + reboot                  = true
      + stop_on_destroy         = true
        tags                    = []
      + timeout_clone           = 1800
      + timeout_create          = 1800
      + timeout_migrate         = 1800
      + timeout_move_disk       = 1800
      + timeout_reboot          = 1800
      + timeout_shutdown_vm     = 1800
      + timeout_start_vm        = 1800
      + timeout_stop_vm         = 300
        # (13 unchanged attributes hidden)
        # (9 unchanged blocks hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```
5. VM is now rebooting

**Expected behavior**
VM is not expected to reboot for this kind of changes

**Additional context**

- Single or clustered Proxmox: signle Proxmox 7.4-17
- Provider version (ideally it should be the latest version): v0.43.3
- Terraform version: 1.7.0
- OS (where you run Terraform from): Ubuntu 22.04 LTS
- Debug logs (`TF_LOG=DEBUG terraform apply`):

```
2024-01-18T11:49:23.540+0100 [DEBUG] provider.terraform-provider-proxmox_v0.43.3: Sending HTTP Request: tf_http_req_method=GET tf_http_req_uri=/api2/json/nodes/proxmox09/qemu/109/config
2024-01-18T11:49:23.627+0100 [DEBUG] provider.terraform-provider-proxmox_v0.43.3: Received HTTP Response: tf_http_res_status_code=200 tf_resource_type=proxmox_virtual_environment_vm tf_http_res_body="{\"data\":{\"hotplug\":\"network,disk,usb,cpu,memory\",\"smbios1\":\"uuid=8b8a1708-b1da-4ce2-9794-7935805e3dfa\",\"sockets\":1,\"meta\":\"creation-qemu=7.2.0,ctime=1699251231\",\"scsihw\":\"virtio-scsi-pci\",\"nameserver\":\"10.79.10.250 10.79.10.251\",\"tablet\":0,\"bootdisk\":\"scsi0\",\"description\":\"ywh-dev-test-bgpprovider-node00\",\"vmgenid\":\"a737fa02-a1c5-4ae2-acee-a257395a2b7e\",\"scsi1\":\"vms-ssd:vm-109-disk-1,size=4G\",\"numa\":1,\"memory\":1024,\"name\":\"ywh-dev-test-bgpprovider-node00\",\"net0\":\"virtio=62:67:4A:75:14:CE,bridge=vmbr220\",\"tags\":\" \",\"ostype\":\"l26\",\"cores\":1,\"onboot\":1,\"kvm\":1,\"searchdomain\":\"contoso.com\",\"ide2\":\"none,media=cdrom\",\"agent\":\"1\",\"ide0\":\"vms-ssd:vm-109-cloudinit,media=cdrom,size=4M\",\"cpu\":\"host\",\"boot\":\"c\",\"ipconfig0\":\"ip=10.79.220.1/24,gw=10.79.220.254\",\"bios\":\"seabios\",\"scsi0\":\"vms-ssd:vm-109-disk-0,size=8G\",\"digest\":\"61c53b34d85243352b6b24deb3582f59718b342e\"}}" tf_http_res_status_reason="200 OK"
2024-01-18T11:49:23.633+0100 [DEBUG] provider.terraform-provider-proxmox_v0.43.3: Sending HTTP Request: tf_http_req_body="keyboard=en-us&name=ywh-dev-test-bgpprovider-node00&onboot=1" tf_http_req_method=PUT tf_http_req_uri=/api2/json/nodes/proxmox09/qemu/109/config @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/logging/logging_http_transport.go:162 tf_mux_provider=tf5to6server.v5tov6Server tf_provider_addr=registry.terraform.io/bpg/proxmox timestamp="2024-01-18T11:49:23.633+0100"
2024-01-18T11:49:23.672+0100 [DEBUG] provider.terraform-provider-proxmox_v0.43.3: Received HTTP Response: tf_http_res_body="{\"data\":null}"
2024-01-18T11:49:23.673+0100 [DEBUG] provider.terraform-provider-proxmox_v0.43.3: Sending HTTP Request: tf_http_req_uri=/api2/json/nodes/proxmox09/qemu/109/status/current tf_http_req_method=GET
2024-01-18T11:49:23.705+0100 [DEBUG] provider.terraform-provider-proxmox_v0.43.3: Received HTTP Response: tf_http_res_body="{\"data\":{\"agent\":1,\"maxdisk\":8589934592,\"running-qemu\":\"7.2.0\",\"cpus\":1,\"proxmox-support\":{\"backup-max-workers\":true,\"pbs-dirty-bitmap\":true,\"pbs-masterkey\":true,\"pbs-dirty-bitmap-savevm\":true,\"pbs-dirty-bitmap-migration\":true,\"query-bitmap-info\":true,\"pbs-library-version\":\"1.3.1 (4d450bb294cac5316d2f23bf087c4b02c0543d79)\"},\"diskwrite\":2059261952,\"disk\":0,\"balloon\":1073741824,\"blockstat\":{\"ide2\":{\"wr_operations\":0,\"account_failed\":true,\"failed_unmap_operations\":0,\"invalid_flush_operations\":0,\"failed_flush_operations\":0,\"rd_operations\":5,\"invalid_rd_operations\":0,\"flush_total_time_ns\":0,\"failed_wr_operations\":0,\"failed_rd_operations\":0,\"unmap_bytes\":0,\"unmap_operations\":0,\"account_invalid\":true,\"rd_bytes\":158,\"unmap_merged\":0,\"wr_merged\":0,\"invalid_unmap_operations\":0,\"wr_total_time_ns\":0,\"timed_stats\":[],\"invalid_wr_operations\":0,\"wr_bytes\":0,\"unmap_total_time_ns\":0,\"idle_time_ns\":4837412664360,\"rd_merged\":0,\"rd_total_time_ns\":41593,\"wr_highest_offset\":0,\"flush_operations\":0},\"scsi1\":{\"invalid_flush_operations\":0,\"failed_unmap_operations\":0,\"failed_flush_operations\":0,\"wr_operations\":65,\"account_failed\":true,\"unmap_operations\":5,\"account_invalid\":true,\"unmap_bytes\":4292870144,\"invalid_rd_operations\":0,\"flush_total_time_ns\":585449,\"rd_operations\":777,\"failed_rd_operations\":0,\"failed_wr_operations\":0,\"timed_stats\":[],\"invalid_wr_operations\":0,\"unmap_merged\":0,\"rd_bytes\":19596288,\"invalid_unmap_operations\":0,\"wr_merged\":0,\"wr_total_time_ns\":160690756,\"wr_highest_offset\":4294967296,\"flush_operations\":22,\"wr_bytes\":136634368,\"unmap_total_time_ns\":31982,\"idle_time_ns\":4428943873335,\"rd_merged\":0,\"rd_total_time_ns\":99222805},\"scsi0\":{\"timed_stats\":[],\"invalid_wr_operations\":0,\"unmap_merged\":0,\"rd_bytes\":937011200,\"wr_total_time_ns\":26605435406,\"wr_merged\":0,\"invalid_unmap_operations\":0,\"wr_highest_offset\":8119422976,\"flush_operations\":7176,\"unmap_total_time_ns\":0,\"wr_bytes\":1922627584,\"rd_total_time_ns\":3004584519,\"idle_time_ns\":2437533243,\"rd_merged\":0,\"invalid_flush_operations\":0,\"failed_unmap_operations\":0,\"failed_flush_operations\":0,\"wr_operations\":18059,\"account_failed\":true,\"account_invalid\":true,\"unmap_operations\":0,\"unmap_bytes\":0,\"flush_total_time_ns\":119393570,\"invalid_rd_operations\":0,\"rd_operations\":21785,\"failed_rd_operations\":0,\"failed_wr_operations\":0},\"ide0\":{\"account_failed\":true,\"wr_operations\":0,\"failed_flush_operations\":0,\"invalid_flush_operations\":0,\"failed_unmap_operations\":0,\"failed_rd_operations\":0,\"failed_wr_operations\":0,\"flush_total_time_ns\":0,\"invalid_rd_operations\":0,\"rd_operations\":111,\"unmap_operations\":0,\"account_invalid\":true,\"unmap_bytes\":0,\"wr_total_time_ns\":0,\"invalid_unmap_operations\":0,\"wr_merged\":0,\"unmap_merged\":0,\"rd_bytes\":409810,\"invalid_wr_operations\":0,\"timed_stats\":[],\"rd_total_time_ns\":5710951,\"idle_time_ns\":4440390532283,\"rd_merged\":0,\"wr_bytes\":0,\"unmap_total_time_ns\":0,\"flush_operations\":0,\"wr_highest_offset\":0}},\"qmpstatus\":\"running\",\"uptime\":4847,\"netout\":2934260,\"maxmem\":1073741824,\"ballooninfo\":{\"mem_swapped_in\":159744,\"free_mem\":166227968,\"last_update\":1705574963,\"max_mem\":1073741824,\"actual\":1073741824,\"total_mem\":959053824,\"mem_swapped_out\":491520,\"major_page_faults\":2770,\"minor_page_faults\":4119480},\"cpu\":0.00724310558415304,\"mem\":792825856,\"pid\":775821,\"freemem\":166227968,\"vmid\":109,\"status\":\"running\",\"ha\":{\"managed\":0},\"nics\":{\"tap109i0\":{\"netin\":179128299,\"netout\":2934260}},\"netin\":179128299,\"name\":\"ywh-dev-test-bgpprovider-node00\",\"diskread\":957017456,\"tags\":\" \",\"running-machine\":\"pc-i440fx-7.2+pve0\"}}"
2024-01-18T11:49:23.706+0100 [DEBUG] provider.terraform-provider-proxmox_v0.43.3: Sending HTTP Request: tf_http_req_method=POST tf_http_req_uri=/api2/json/nodes/proxmox09/qemu/109/status/reboot
```

### LINKED ISSUE #2295: vm: Unnecessary changes after importing a VM
**Describe the bug**
After importing a VM, I expect `terraform plan` to report no changes, but it doesn’t.

**To Reproduce**

1. Create a VM manually.
2. Run `terraform import` to import the VM.
3. Run `terraform plan`.

### PR DESCRIPTION
**Pull request by hsnprsd**
### Contributor's Note

- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [x] I have added / updated acceptance tests in `/fwprovider/tests` for any new or updated resources / data sources.
- [x] I have ran `make example` to verify that the change works as expected.

### Proof of Work

See new acceptance test.

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #932 
Closes #2295

### CODE REVIEW

**Comment by hsnprsd** [comment]
Closes #2295

File: proxmoxtf/resource/vm/vm.go [hunk 1]
```diff
@@ -2706,38 +2706,11 @@ func vmCreateCustom(ctx context.Context, d *schema.ResourceData, m interface{})
...
 	}
 
-	var bootOrderConverted []string
-	if cdromInterface != "" {
-		bootOrderConverted = []string{cdromInterface}
-	}
-
 	bootOrder := d.Get(mkBootOrder).([]interface{})
 
-	if len(bootOrder) == 0 {
```
Comment (hsnprsd) [inline proxmoxtf/resource/vm/vm.go:2734]: I removed these shenanigans 😆, but I don't know if that is what we want. Proxmox itself sets the `boot` field to `order=any` if the `boot` field is not provided.

**Comment by TobiPeterG** [comment]
There's no proof of work or an example that leads to the issue, how should it be reproduced or checked if it works?

Please provide the config of a VM that is imported and the opentofu config of the imported VM and where the "unnecessary" changes occur.

**Comment by hsnprsd** [comment]
You can run the test I added without the changes I made and see it yourself 😄 There are so many fields in the VM resource that are not set in the read function but they have a default value in the schema. Those fields will trigger a change after when running `terraform plan` after the VM is imported.

File: proxmoxtf/resource/vm/network/network.go [hunk 2]
```diff
@@ -142,85 +147,42 @@ func ReadNetworkDeviceObjects(d *schema.ResourceData, vmConfig *vms.GetResponseD
...
+				mkNetworkDeviceQueues:       valueOrDefault(netDevice.Queues, 0),
+				mkNetworkDeviceRateLimit:    valueOrDefault(netDevice.RateLimit, 0),
+				mkNetworkDeviceVLANID:       valueOrDefault(netDevice.Tag, 0),
+				mkNetworkDeviceMTU:          valueOrDefault(netDevice.MTU, 0),
+				mkNetworkDeviceTrunks: func(trunks []int) string {
+					if trunks == nil {
+						return ""
+					}
 
-	if len(currentNetworkDeviceList) > 0 || networkDeviceLast > -1 {
```
Comment (bpg-dev) [inline proxmoxtf/resource/vm/network/network.go]: hm.. looks like this condition got dropped from the new code.
was it intentional?

File: proxmoxtf/resource/vm/vm.go (hunk 1 above)
Comment (bpg-dev) [reply proxmoxtf/resource/vm/vm.go:2734]: not sure if this change did it, but something is broken in this branch.
the vm is not properly starting in tests, works in `main` tho.

Image

Image

Comment (hsnprsd) [reply proxmoxtf/resource/vm/vm.go:2734]: You are right. When using `file_id`, the VM does not have a disk attached when created and Proxmox does not include the disk in the boot order. You might be booting from the cloud init drive which is not correct. I reverted the computation of boot order.

File: proxmoxtf/resource/vm/network/network.go (hunk 2 above)
Comment (hsnprsd) [reply proxmoxtf/resource/vm/network/network.go]: Yes. I don't know why we had the condition in the first place. This function is used in the vm read function and I don't think we should care about the state data while reading the network devices.

Comment (bpg-dev) [reply proxmoxtf/resource/vm/network/network.go]: I believe this is related to the clone use case, we have a relevant discussion [here](https://github.com/bpg/terraform-provider-proxmox/pull/2260).

Imagine a use case with two VMs: `template` and `clone`. The template has a network interface defined in the config, while the clone doesn't. When the template is cloned by PVE, the network interface gets copied to the clone, which is the intended behavior. When the provider reads the clone back at the end of the create operation, it sees this network device. However, this device should not be added to the state since it was not part of the initial config.

Things get complicated when the user wants to define other interfaces in the clone that do not match those in the template. This leads to all the complex conditional logic that looks confusing at first glance. All of this originated from the legacy provider, which had one crucial design flaw: resources were managed as lists instead of maps, where the actual device name would be used as a key.

So I'm not entirely sure whether this change breaks the cloning use cases, and if it does, to what extent. I also can’t say confidently whether it should be reverted or can go in as is. The acceptance tests are not as stable or reliable as I’d like them to be, and I currently don’t have a good solution to run them in CI. For now, I’m relying mostly on manual testing, which takes time and effort. Please bear with me on this PR — I’ll get to it soon.

Comment (hsnprsd) [reply proxmoxtf/resource/vm/network/network.go]: Got it. I added a test for cloning a VM that has a network device defined in the template, and it works fine. I don’t quite follow the scenario you described—why shouldn’t the network device be added to the state? As far as I can tell, everything works smoothly as long as the user doesn’t explicitly define network devices on the clone. When they do, they just need to include the existing ones as well.

**Comment by bpg-dev** [comment]
Ok, there is a conflict on the vm's network code, which was refactored in #2260
I'm going to merge `main`, and take the `main`'s version of it as-is.

File: proxmoxtf/resource/vm/vm.go [hunk 3]
```diff
@@ -4896,6 +4896,90 @@ func vmReadCustom(
...
+	}
+
+	if _, ok := d.GetOk(mkTimeoutMoveDisk); !ok {
+		err := d.Set(mkTimeoutMoveDisk, dvTimeoutMoveDisk)
+		if err != nil {
+			diags = append(diags, diag.FromErr(e)...)
+		}
+	}
+
+	if _, ok := d.GetOk(mkStopOnDestroy); !ok {
```
Comment (bpg-dev) [inline proxmoxtf/resource/vm/vm.go]: for boolean fields we should be using `GetOkExists`. It's deprecated, but essentially we don't want to overwrite, e.g. with false if a value is not defined in the config.
