### PR TITLE
fix(vm): hostpci devices not showing up in refresh plan

### LINKED ISSUE #577: hostpciX not handled correctly when planning
**Describe the bug**
We are currently on our way to upgrade the terraform-provider-proxmox to the latest version. This includes handling manual configuration that could not be applied via terraform with older versions of the provider (in our case hostpci devices).

After adding the hostpci devices to the vm resources (again, those devices have been previously added to the vms by hand because this was not possible with this provide in older versions), `terraform plan` tries to add these devices. I'm not that familiar with terraform in order to decide whether this is working as intended or not, but I concluded that it is and that I have to `terraform plan -refresh-only` in order to update my terraform state to the real state.

This however does not include the hostpci device entries in the refresh plan.

**To Reproduce**
1. Create a vm resource without a hostpci device
2. Run `terraform apply`
3. Manually add a hostpci device to the vm
4. Modify the vm resource by adding the very same hostpci device
5. Run `terraform plan -refresh-only`
6. The hostpci device is not included in the refresh plan

```terraform
resource "proxmox_virtual_environment_vm" "recreate_when_hostpci_changes" {
  name        = "recreate-when-hostpci-changes"
  description = "## TEST recreate-when-hostpci-changes"

  node_name = "foo"

  started = false

  cpu {
    cores = 1
  }

  memory {
    dedicated = 512
  }

  operating_system {
    type = "l26"
  }

  network_device {
    bridge = "vmbr0"
  }

### only add this after the vm has been created
#  hostpci {
#   device = "hostpci0"
#    id = "81:00.8"
#    rombar = true
#  }
}
```

**Expected behavior**
I would expect the hostpci device to appear in the refresh plan.

### PR DESCRIPTION
**Pull request by michaelze**
### Contributor's Note
Please mark the following items with an [x] if they apply to your PR.
Leave the [ ] if they are not applicable, or if you have not completed the item.
- [ ] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated templates in `/example` for any new or updated resources / data sources.
- [ ] I have ran `make example` to verify that the change works as expected. 

This PR fixes hostpci devices not being present when retrieving the state from proxmox (e.g. needed for refresh plans). In addition, the `UnmarshalJSON` for `CustomPCIDevice` was updated to match proxmox's default values when only a device id is present. Also, the respective test now actually performs assertions for non-error cases 😇.

@bpg Please advise on documentation (`/docs`) to add (if any)

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #577

### CODE REVIEW

File: proxmoxtf/resource/vm.go [hunk 1]
```diff
@@ -3997,7 +3996,7 @@ func vmReadCustom(
 		pciMap[pi] = pci
 	}
 
-	if len(currentPCIList) > 0 {
```
Comment (bpg-dev) [inline proxmoxtf/resource/vm.go:4391]: Hmmmmm... this looks a bit suspicious -- it will write the to the state regardless if the plan has hostpci defined or not, which may cause some side-effects.
I'd like to spend some more time testing the change.

Comment (michaelze) [reply proxmoxtf/resource/vm.go:4391]: Thanks for your feedback! It is very much possible that I misunderstood the code that I changed.
Anyway, during my tests, `currentPCIList` was empty which lead to the fix I provided. Does `schema.ResourceData` (that's where currrentPCIList is taken from) represent the Terraform inventory or the current state?

Comment (bpg-dev) [reply proxmoxtf/resource/vm.go:4391]: To be clear, when i said "state" and "plan" i meant both TF state and TF plan, regardless what is in PVE.

In this context, `d schema.ResourceData` represent them both, when it is used in "Create" operation. `d.Get` returns an attribute from the currently applying plan, `d.Set` sets an attribute that then will be written to the state at the end of apply.

So with this change _I think_ is possible to have a situation when hostpci is not defined in the plan, but exists in the VM in PVE - for example, if VM is cloned form one that has hostpci. In this case TF will write in the state those extra attributes at the end. Then if you re-apply the exact same plan, TF will detect discrepancy between plan and state - the hostpci section is not in the plan but is in the state, and will try to remove hostpci.

Again, this is just a suspicious at the moment, after looking at the code. I haven't had a chance to test this case properly yet.

Comment (bpg-dev) [reply proxmoxtf/resource/vm.go:4391]: I was able to reproduce the situation I was describing above.

Template:
```hcl
resource "proxmox_virtual_environment_vm" "ubuntu_vm" {
  name = "578-hostpci"
  node_name = "pve"
  vm_id     = 578

  hostpci {
    device = "hostpci0"
    id = "0000:01:00.0"
    pcie = true
  }

  started = false
}

resource "proxmox_virtual_environment_vm" "ubuntu_vm_cloned" {
  depends_on = [proxmox_virtual_environment_vm.ubuntu_vm]
  name = "579-hostpci-cloned"
  node_name = "pve"
  vm_id     = 579

  clone {
    vm_id = 578
  }

  started = false
}
```

After `terrafrom apply` the cloned VM got deployed with its `hostpci` device:
Screenshot 2023-09-24 at 8 43 31 PM

But after the second apply, without any changes to the plan, the `hostpci` in the clone got removed:
```
...
 # proxmox_virtual_environment_vm.ubuntu_vm_cloned will be updated in-place
  ~ resource "proxmox_virtual_environment_vm" "ubuntu_vm_cloned" {
        id                      = "579"
      + mac_addresses           = (known after apply)
        name                    = "579-hostpci-cloned"
        # (22 unchanged attributes hidden)

      - hostpci {
          - device = "hostpci0" -> null
          - id     = "0000:01:00.0" -> null
          - pcie   = true -> null
          - rombar = false -> null
          - xvga   = false -> null
        }

        # (1 unchanged block hidden)
    }
...
```
Screenshot 2023-09-24 at 8 44 33 PM

Comment (bpg-dev) [reply proxmoxtf/resource/vm.go:4391]: I've also tried to reproduce the original issue (as described in #577) on v0.32.0:

Template:
```hcl
resource "proxmox_virtual_environment_vm" "ubuntu_vm" {
  name = "578-hostpci"
  node_name = "pve"
  vm_id     = 578

#  hostpci {
#    device = "hostpci0"
#    id = "0000:01:00.0"
#    pcie = true
#  }

  started = false
}
```

Apply, then uncomment the `hostpci` block, and apply again: the `hostpci` devices got created 🤔
```
proxmox_virtual_environment_vm.ubuntu_vm: Refreshing state... [id=578]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # proxmox_virtual_environment_vm.ubuntu_vm will be updated in-place
  ~ resource "proxmox_virtual_environment_vm" "ubuntu_vm" {
        id                      = "578"
        name                    = "578-hostpci"
        tags                    = []
        # (23 unchanged attributes hidden)

      - cpu {
          - cores      = 1 -> null
          - flags      = [] -> null
          - hotplugged = 0 -> null
          - numa       = false -> null
          - sockets    = 1 -> null
          - type       = "qemu64" -> null
          - units      = 1024 -> null
        }

      + hostpci {
          + device = "hostpci0"
          + id     = "0000:01:00.0"
          + pcie   = true
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
(i know there are some issues with `cpu` section, but it is a different story :)
 
Screenshot 2023-09-24 at 8 56 48 PM

Wondering, if I'm missing something in the use case?

**Comment by bpg** [comment]
Hi @michaelze!

I'm not sure in which state this PR is. The issue it's trying to fix seems to be not reproducible (at least in my tests).
Are you still looking to merge this? Then having a template that reproduces the issue will help a lot. If not, I'd like to close the PR.

Thanks!

**Comment by michaelze** [comment]
Hi @bpg! I was finally able to come back to this issue and did some further digging. I also updated my local setup to the latest version (v0.40.0).

First of all, I'd like to clarify when this issue occurs:

```
resource "proxmox_virtual_environment_vm" "test-update-hostpci" {
  name        = "test-update-hostpci"
  description = "test-update-hostpci"

  node_name = "pve"

  started = false
}

```

1. Create a VM without hostpci device
2. terraform apply
3. VM gets created correctly
4. Assume you did this a long time ago when hostpci was not yet integrated into the terraform-provider-proxmox :wink: and manually add a pci device via pve
5. Assume time flew by, the maintainer of the provider did an awesome job on integrating all these new features including hostpci support :wink: and add a hostpci device to your terraform setup

```
resource "proxmox_virtual_environment_vm" "test-update-hostpci" {
  name        = "test-update-hostpci"
  description = "test-update-hostpci"

  node_name = "pve"

  started = false

  hostpci {
    device = "hostpci0"
    id = "0000:81:02.5"
    rombar = true
  }
}
```
6. As your environment no longer matches your state (but should match the resource definition above), do a `terraform apply --refresh-only
7. Expect the hostpci device being added to the vm in your state
8. It is not 😞 

The same is true, if you use the resource definition including the hostpci device and do an import of the resource into an empty state `terraform import proxmox_virtual_environment_vm.test-update-hostpci pve/123`. The state contains the virtual machine but without the hostpci device.

So as for your comment above ("it will write the to the state regardless if the plan has hostpci defined or not"): the issue with the current behavior is, that the hostpci device will not be part of the state, if it (or another hostpci device) is not yet part of the state.

I admit it is a bit of an edge case and I hope I'm using terraform correctly (although apart from the `--refresh-only` part, I'm pretty sure, I use `import` the way it is meant to be used and my expectations are also correct) and that I was also able to make my issue more clear.

As you are more familiar with the code base can you tell me whether I discovered just a bug or rather a missing feature and how I could fix/implement this behavior?

Thanks a lot!

**Comment by bpg** [comment]
Ok, now I understand, thanks for explanation :)

The problem is in this [code block](https://github.com/bpg/terraform-provider-proxmox/blob/main/proxmoxtf/resource/vm.go#L4391-L4395): the provider reads the devices, but "sets" them in the state only if there were devices in the state previously.
That's a bug.

**Review by bpg — APPROVED** [review]
LGTM! 🚀

**Comment by michaelze** [comment]
Thank you very much! Your quick responses and actions are always appreciated!
