### PR TITLE
fix(lxc): support `device_passthrough` config on non-clone container

### LINKED ISSUE #1721: Device Passthrough in LXC only works on resource update
**Describe the bug**
LXC Device Passthrough only works on resource update (adding a new device passthrough to existing LXC). However, when creating the container altogether, the device passthrough is not applied. 

**To Reproduce**

1. Create a resource (LXC)
2. Run `tofu apply`
3. Device passthrough is not applied on creation

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl
resource "proxmox_virtual_environment_download_file" "debian_bookworm_lxc_img" {
  content_type = "vztmpl"
  datastore_id = "local"
  node_name    = "pve1"
  url          = "http://download.proxmox.com/images/system/debian-12-standard_12.2-1_amd64.tar.zst"
}

resource "random_password" "generated" {
  length           = 16
  override_special = "_%@"
  special          = true
}


resource "proxmox_virtual_environment_container" "passthrough" {
  description = "Managed by OpenTofu"

  node_name    = "pve1"
  vm_id        = 360
  tags         = ["opentofu", "debian"]
  started      = true
  unprivileged = false

  cpu {
    cores = 2
    units = 100
  }

  device_passthrough {
    deny_write = false
    gid        = 104
    mode       = "0777"
    path       = "/dev/dri/renderD128"
    uid        = 0
  }

  disk {
    datastore_id = "local-lvm"
    size         = 8
  }

  features {
    mount   = ["nfs"]
    nesting = true
  }

  initialization {
    hostname = "passthrough"

    ip_config {
      ipv4 {
        address = "192.168.24.135/24"
        gateway = "192.168.24.1"
      }
    }

    user_account {
      password = random_password.generated.result
    }
  }

  memory {
    dedicated = 2048
    swap      = 2048
  }

  network_interface {
    name     = "eth0"
    bridge   = "vmbr0"
    enabled  = true
    firewall = false
  }

  operating_system {
    template_file_id = proxmox_virtual_environment_download_file.debian_bookworm_lxc_img.id
    type             = "debian"
  }

  startup {
    order      = "10"
    up_delay   = "60"
    down_delay = "60"
  }
}
```

and the output of `terraform|tofu apply`.
```text
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

OpenTofu will perform the following actions:

  # proxmox_virtual_environment_container.passthrough will be created
  + resource "proxmox_virtual_environment_container" "passthrough" {
      + description    = <<-EOT
            Managed by OpenTofu
        EOT
      + id             = (known after apply)
      + node_name      = "pve1"
      + protection     = false
      + start_on_boot  = true
      + started        = true
      + tags           = [
          + "opentofu",
          + "debian",
        ]
      + template       = false
      + timeout_clone  = 1800
      + timeout_create = 1800
      + timeout_delete = 60
      + timeout_start  = 300
      + timeout_update = 1800
      + unprivileged   = false
      + vm_id          = 360

      + cpu {
          + architecture = "amd64"
          + cores        = 2
          + units        = 100
        }

      + device_passthrough {
          + deny_write = false
          + gid        = 104
          + mode       = "0777"
          + path       = "/dev/dri/renderD128"
          + uid        = 0
        }

      + disk {
          + datastore_id = "local-lvm"
          + size         = 8
        }

      + features {
          + fuse    = false
          + keyctl  = false
          + mount   = [
              + "nfs",
            ]
          + nesting = true
        }

      + initialization {
          + hostname = "passthrough"

          + ip_config {
              + ipv4 {
                  + address = "192.168.24.135/24"
                  + gateway = "192.168.24.1"
                }
            }

          + user_account {
              + password = (sensitive value)
            }
        }

      + memory {
          + dedicated = 2048
          + swap      = 2048
        }

      + network_interface {
          + bridge     = "vmbr0"
          + enabled    = true
          + firewall   = false
          + mtu        = 0
          + name       = "eth0"
          + rate_limit = 0
          + vlan_id    = 0
        }

      + operating_system {
          + template_file_id = (known after apply)
          + type             = "debian"
        }

      + startup {
          + down_delay = 60
          + order      = 10
          + up_delay   = 60
        }
    }

  # proxmox_virtual_environment_download_file.debian_bookworm_lxc_img will be created
  + resource "proxmox_virtual_environment_download_file" "debian_bookworm_lxc_img" {
      + content_type        = "vztmpl"
      + datastore_id        = "local"
      + file_name           = (known after apply)
      + id                  = (known after apply)
      + node_name           = "pve1"
      + overwrite           = true
      + overwrite_unmanaged = false
      + size                = (known after apply)
      + upload_timeout      = 600
      + url                 = "http://download.proxmox.com/images/system/debian-12-standard_12.2-1_amd64.tar.zst"
      + verify              = true
    }

  # random_password.generated will be created
  + resource "random_password" "generated" {
      + bcrypt_hash      = (sensitive value)
      + id               = (known after apply)
      + length           = 16
      + lower            = true
      + min_lower        = 0
      + min_numeric      = 0
      + min_special      = 0
      + min_upper        = 0
      + number           = true
      + numeric          = true
      + override_special = "_%@"
      + result           = (sensitive value)
      + special          = true
      + upper            = true
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

proxmox_virtual_environment_download_file.debian_bookworm_lxc_img: Creating...
random_password.generated: Creating...
random_password.generated: Creation complete after 0s [id=none]
proxmox_virtual_environment_download_file.debian_bookworm_lxc_img: Still creating... [10s elapsed]
proxmox_virtual_environment_download_file.debian_bookworm_lxc_img: Still creating... [20s elapsed]
proxmox_virtual_environment_download_file.debian_bookworm_lxc_img: Creation complete after 22s [id=local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst]
proxmox_virtual_environment_container.passthrough: Creating...
proxmox_virtual_environment_container.passthrough: Creation complete after 6s [id=360]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

**Expected behavior**
The device passthrough should work on resource creation as well.

**Screenshots**

Image

**Additional context**

- Single or clustered Proxmox: single
- Proxmox version: 8.3.1
- Provider version (ideally it should be the latest version): 0.70
- Terraform/OpenTofu version: OpenTofu v1.8.7
- OS (where you run Terraform/OpenTofu from): Manjaro
- Debug logs (`TF_LOG=DEBUG terraform apply`):

Request to Proxmox API log:
```
@module=proxmox
Accept=application/json
Host=pve1.dhimas.net:8006
tf_http_op_type=request
tf_http_req_method=POST
tf_http_req_version=HTTP/1.1
tf_http_trans_id=72ad56df-290c-6af7-6c38-ff29655417ed
tf_req_id=bc585168-55cd-56a8-1146-ccdea087667b
tf_resource_type=proxmox_virtual_environment_container
tf_mux_provider=tf5to6server.v5tov6Server
@caller=/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/logging/logging_http_transport.go:162
Accept-Encoding=gzip
Content-Type=application/x-www-form-urlencoded
Csrfpreventiontoken=678E741E:E3CkipLZNb1fe2dOkOG4rtlsf8yOa4A8EfuouelHwg4
User-Agent=Go-http-client/1.1
tf_http_req_body="arch=amd64&cmode=tty&console=1&cores=2&cpuunits=100&description=Managed+by+OpenTofu&features=mount%3Dnfs%2Cnesting%3D1&hostname=passthrough&memory=2048&net0=bridge%3Dvmbr0%2Cip%3D192.168.24.135%2F24%2Cgw%3D192.168.24.1%2Cname%3Deth0&onboot=1&ostemplate=local%3Avztmpl%2Fdebian-12-standard_12.2-1_amd64.tar.zst&ostype=debian&password=SL8KtjYPl4O73x9y&protection=0&rootfs=volume%3Dlocal-lvm%3A8&start=1&startup=down%3D60%2Corder%3D10%2Cup%3D60&storage=local-lvm&swap=2048&tags=debian%3Bopentofu&template=0&tty=2&unprivileged=0&vmid=360"
tf_http_req_uri=/api2/json/nodes/pve1/lxc
tf_provider_addr=registry.terraform.io/bpg/proxmox
tf_rpc=ApplyResourceChange
Content-Length=533
Cookie="<obscured>"
timestamp="2025-01-20T23:04:46.077+0700"
```

### PR DESCRIPTION
**Pull request by gifff**
### Contributor's Note

- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [x] I have added / updated acceptance tests in `/fwprovider/tests` for any new or updated resources / data sources.
- [ ] I have ran `make example` to verify that the change works as expected.

### Proof of Work

swappy-20250121_002457

Debug log on LXC resource create:
```
2025-01-20T23:36:57.829+0700 [DEBUG] provider.terraform-provider-proxmox_v0.70.0: Sending HTTP Request: 
  Host=pve1.dhimas.net:8006
  tf_http_req_method=POST
  tf_provider_addr=registry.terraform.io/bpg/proxmox
  tf_resource_type=proxmox_virtual_environment_container
  @caller=/home/gifary/.asdf/installs/golang/1.23.3/packages/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/logging/logging_http_transport.go:162
  Content-Type=application/x-www-form-urlencoded
  Csrfpreventiontoken=678E7BA9:Cwo7LdHSwZ2gvbIXX0Rz36J2/YuWPE0Wl4D7idsQMZY
  tf_http_req_body="arch=amd64&cmode=tty&console=1&cores=2&cpuunits=100&description=Managed+by+OpenTofu&dev0=deny-write%3D0%2Cpath%3D%2Fdev%2Fdri%2FrenderD128%2Cuid%3D0%2Cgid%3D104%2Cmode%3D0777&features=mount%3Dnfs%2Cnesting%3D1&hostname=passthrough&memory=2048&net0=bridge%3Dvmbr0%2Cip%3D192.168.24.135%2F24%2Cgw%3D192.168.24.1%2Cname%3Deth0&onboot=1&ostemplate=local%3Avztmpl%2Fdebian-12-standard_12.2-1_amd64.tar.zst&ostype=debian&password=awOz3zjE55O8%40Zl%40&protection=0&rootfs=volume%3Dlocal-lvm%3A8&start=1&startup=down%3D60%2Corder%3D10%2Cup%3D60&storage=local-lvm&swap=2048&tags=debian%3Bopentofu&template=0&tty=2&unprivileged=0&vmid=360"
  tf_http_req_version=HTTP/1.1
  tf_http_trans_id=9161ebd9-2035-4185-de1b-e0d2c73b5060
  tf_rpc=ApplyResourceChange
  @module=proxmox
  Content-Length=628
  Accept-Encoding=gzip
  Cookie="<obscured>"
  tf_http_op_type=request
  tf_http_req_uri=/api2/json/nodes/pve1/lxc
  tf_mux_provider=tf5to6server.v5tov6Server
  Accept=application/json
  tf_req_id=7686f97f-d060-979a-65ef-f5b7a525b5ed
  User-Agent=Go-http-client/1.1
  timestamp="2025-01-20T23:36:57.829+0700"
```

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #1721

### CODE REVIEW

**Comment by gifff** [comment]
I have only done manual testing so far

**Comment by bpg** [comment]
Hey @gifff! 👋🏼 
Thank you for contributing this fix.

I see it is still WIP, but I took a pick. I think the code needs some adjustments as the updated test is failing now:
```
--- FAIL: TestAccResourceContainer (1.13s)
    --- FAIL: TestAccResourceContainer/clone_container (47.96s)
        resource_container_test.go:266: Step 1/1 error: After applying this test step, the non-refresh plan was not empty.
            stdout:
            
            
            Terraform used the selected providers to generate the following execution
            plan. Resource actions are indicated with the following symbols:
              ~ update in-place
            
            Terraform will perform the following actions:
            
              # proxmox_virtual_environment_container.test_container_clone will be updated in-place
              ~ resource "proxmox_virtual_environment_container" "test_container_clone" {
                    id             = "145746"
                    # (12 unchanged attributes hidden)
            
                  - device_passthrough {
                      - deny_write = false -> null
                      - gid        = 0 -> null
                      - path       = "/dev/zero" -> null
                      - uid        = 0 -> null
                        # (1 unchanged attribute hidden)
                    }
            
                    # (2 unchanged blocks hidden)
                }
            
            Plan: 0 to add, 1 to change, 0 to destroy.
FAIL
FAIL    github.com/bpg/terraform-provider-proxmox/fwprovider/test       185.120s
```

I'll be able to take a closer look later in the week and help you sort it out.

File: proxmoxtf/resource/container/container.go [hunk 1]
```diff
@@ -2361,8 +2390,10 @@ func containerRead(ctx context.Context, d *schema.ResourceData, m interface{}) d
 		devicePassthroughList = append(devicePassthroughList, devicePassthrough)
 	}
 
+	currentDevicePassthrough := d.Get(mkDevicePassthrough).([]interface{})
+
 	if len(clone) > 0 {
-		if len(devicePassthroughList) > 0 {
+		if len(currentDevicePassthrough) > 0 {
```
Comment (bpg-dev) [inline proxmoxtf/resource/container/container.go:2396]: good catch! 👍🏼

**Review by bpg — APPROVED** [review]
Thanks for the fix @gifff, much appreciated!

LGTM! 🚀

**Comment by bpg** [comment]
@all-contributors please add @gifff for code, bug
