### PR TITLE
fix(apt): add missing Ceph Squid

### LINKED ISSUE #2316: Ceph Squid is missing in CephVersionName
**Describe the bug**
It has been added to the docs via #2044 but it is still missing in `proxmox/types/nodes/apt/ceph_version_name.go`

This only affects PVE9.

Related problem: #2219 

**To Reproduce**

```hcl
resource "proxmox_virtual_environment_apt_standard_repository" "example" {
  handle = "ceph-squid-no-subscription"
  node   = "pve"
}
```

**Expected behavior**
It succeeds.

- Single or clustered Proxmox: Single
- Proxmox version: 9.0
- Provider version (ideally it should be the latest version): 0.86.0
- Terraform/OpenTofu version: Terraform v1.13.4
- OS (where you run Terraform/OpenTofu from): Fedora Silverblue

### PR DESCRIPTION
**Pull request by maciej-lech**
### Contributor's Note

- [ ] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [ ] I have added / updated acceptance tests in `/fwprovider/tests` for any new or updated resources / data sources.
- [X] I have ran `make example` to verify that the change works as expected.

### Proof of Work

CI's `make test` should be enough

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #2316

### CODE REVIEW

File: proxmox/types/nodes/apt/repositories/ceph_version_name_test.go [hunk 1]
```diff
@@ -0,0 +1,201 @@
...
+	}
+
+	for name, test := range tests {
+		t.Run(name, func(t *testing.T) {
+			t.Parallel()
+
+			result, err := ParseCephVersionName(test.input)
+
+			if test.expectError {
+				if err == nil {
```
Comment (shamilovstas) [inline proxmox/types/nodes/apt/repositories/ceph_version_name_test.go]: `require.Error(err)`

File: proxmox/types/nodes/apt/repositories/ceph_version_name_test.go [hunk 2]
```diff
@@ -0,0 +1,201 @@
...
+					t.Errorf("expected error for input %q, got nil", test.input)
+				}
+			} else {
+				if err != nil {
```
Comment (shamilovstas) [inline proxmox/types/nodes/apt/repositories/ceph_version_name_test.go]: `require.NoError(err)`

File: proxmox/types/nodes/apt/repositories/ceph_version_name_test.go [hunk 3]
```diff
@@ -0,0 +1,201 @@
...
+					t.Errorf("unexpected error for input %q: %v", test.input, err)
+				}
+
+				if result != test.expected {
```
Comment (shamilovstas) [inline proxmox/types/nodes/apt/repositories/ceph_version_name_test.go]: `assert.Equal`

File: proxmox/types/nodes/apt/repositories/ceph_version_name_test.go [hunk 4]
```diff
@@ -0,0 +1,201 @@
...
+			expected: "unknown",
+		},
+	}
+
+	for name, test := range tests {
+		t.Run(name, func(t *testing.T) {
+			t.Parallel()
+
+			result := test.version.String()
+			if result != test.expected {
```
Comment (shamilovstas) [inline proxmox/types/nodes/apt/repositories/ceph_version_name_test.go]: assert.Equal

File: proxmox/types/nodes/apt/repositories/ceph_version_name_test.go [hunk 5]
```diff
@@ -0,0 +1,201 @@
...
+			expected: `"unknown"`,
+		},
+	}
+
+	for name, test := range tests {
+		t.Run(name, func(t *testing.T) {
+			t.Parallel()
+
+			result, err := json.Marshal(test.version)
+			if err != nil {
```
Comment (shamilovstas) [inline proxmox/types/nodes/apt/repositories/ceph_version_name_test.go]: require.NoError

File: proxmox/types/nodes/apt/repositories/ceph_version_name_test.go [hunk 6]
```diff
@@ -0,0 +1,201 @@
...
+				t.Errorf("unexpected error: %v", err)
+			}
+
+			if string(result) != test.expected {
```
Comment (shamilovstas) [inline proxmox/types/nodes/apt/repositories/ceph_version_name_test.go]: assert.Equal

File: proxmox/types/nodes/apt/repositories/ceph_version_name_test.go [hunk 7]
```diff
@@ -0,0 +1,201 @@
...
+
+	for name, test := range tests {
+		t.Run(name, func(t *testing.T) {
+			t.Parallel()
+
+			var result CephVersionName
+			err := json.Unmarshal([]byte(test.input), &result)
+
+			if test.expectError {
+				if err == nil {
```
Comment (shamilovstas) [inline proxmox/types/nodes/apt/repositories/ceph_version_name_test.go]: require.Error

File: proxmox/types/nodes/apt/repositories/ceph_version_name_test.go [hunk 8]
```diff
@@ -0,0 +1,201 @@
...
+					t.Errorf("expected error for input %q, got nil", test.input)
+				}
+			} else {
+				if err != nil {
+					t.Errorf("unexpected error for input %q: %v", test.input, err)
```
Comment (shamilovstas) [inline proxmox/types/nodes/apt/repositories/ceph_version_name_test.go]: require.NoError

File: proxmox/types/nodes/apt/repositories/ceph_version_name_test.go [hunk 9]
```diff
@@ -0,0 +1,201 @@
...
+				}
+
+				if result != test.expected {
```
Comment (shamilovstas) [inline proxmox/types/nodes/apt/repositories/ceph_version_name_test.go]: assert.Equal
