### PR TITLE
fix(firewall): appending a rule without re-creating the whole ruleset

### LINKED ISSUE #2296: Appending a firewall rule should not destroy and recreate all the existing firewall rules
**Describe the bug**
Currently the firewall rule list is marked as ForceNew: true which causes appending a firewall rule trigger a destroy and recreate of all firewall rules. For example let's say the input policy of the data center is DROP and we allow ssh and proxmox API access in firewall rules. Adding a firewall rule would cause catastrophic issues in this scenario.

**Expected behavior**
I expect the provider to append the new rule to the existing firewall rules.

### PR DESCRIPTION
**Pull request by hsnprsd**
### Contributor's Note

- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [x] I have added / updated acceptance tests in `/fwprovider/tests` for any new or updated resources / data sources.
- [x] I have ran `make example` to verify that the change works as expected.

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #2296

### CODE REVIEW

**Comment by hsnprsd** [comment]
Closes #2296

**Comment by bpg-dev** [comment]
updated the PR title to reflect the actual problem the PR solves.
also added ticket ref to the PR description.

File: proxmoxtf/resource/firewall/rules.go [hunk 1]
```diff
@@ -187,7 +188,7 @@ func Rules() *schema.Resource {
 }
 
 // RulesImport imports firewall rules.
-func RulesImport(ctx context.Context, d *schema.ResourceData, m interface{}) ([]*schema.ResourceData, error) {
+func RulesImport(ctx context.Context, d *schema.ResourceData, m any) ([]*schema.ResourceData, error) {
 	id := d.Id()
```
Comment (bpg-dev) [inline proxmoxtf/resource/firewall/rules.go:192]: I'm totally in favour of cleaning up and modernizing the old code to follow new conventions, but could you possibly extract these changes into a separate PR next time? It would help reduce the cognitive load for reviewers 😅.

File: proxmoxtf/resource/firewall/rules.go [hunk 2]
```diff
@@ -166,9 +165,11 @@ func Rules() *schema.Resource {
 		MkRule: {
 			Type:        schema.TypeList,
 			Description: "List of rules",
-			Required:    true,
-			ForceNew:    true,
-			Elem:        &schema.Resource{Schema: rule},
+			Optional:    true,
```
Comment (bpg-dev) [inline proxmoxtf/resource/firewall/rules.go:168]: should this be `Optional`? what is the use case?

File: proxmoxtf/resource/firewall/rules.go [hunk 3]
```diff
@@ -276,40 +277,29 @@ func RulesImport(ctx context.Context, d *schema.ResourceData, m interface{}) ([]
...
+	if err != nil {
+		diags = append(diags, diag.FromErr(err)...)
+		return diags
+	}
 
-		sg := rule[mkSecurityGroup].(string)
-		if sg != "" {
-			// this is a special case of security group insertion
-			ruleBody = firewall.RuleCreateRequestBody{
-				Action:   sg,
```
Comment (bpg-dev) [inline proxmoxtf/resource/firewall/rules.go:290]: good call adding this check, we should probably update the doc too, to highlight this behaviour.

File: proxmoxtf/resource/firewall/rules.go (hunk 1 above)
Comment (hsnprsd) [reply proxmoxtf/resource/firewall/rules.go:192]: Sorry. I was running golangci-lint 2.6.1 😄

File: proxmoxtf/resource/firewall/rules.go (hunk 2 above)
Comment (hsnprsd) [reply proxmoxtf/resource/firewall/rules.go:168]: Currently there is no way of saying that the firewall rule list must be empty when creating the firewall rules resources.
