### PR TITLE
fix(firewall): update rules with position awareness

### LINKED ISSUE #2575: Firewall: Inserting rule above multiple security group insertion blocks causes failure
**Describe the bug**
Adding a firewall rule before _more than one_ existing security group insertion block, breaks the security group insertion blocks.

**To Reproduce**

1. Create this resource:
```
resource "proxmox_virtual_environment_cluster_firewall_security_group" "foo" {
  name = "foo"

  rule {
    type    = "forward"
    action  = "ACCEPT"
    comment = "Allow access to HTTP"
    dport   = "80"
    proto   = "tcp"
    log     = "nolog"
  }
}

resource "proxmox_virtual_environment_cluster_firewall_security_group" "bar" {
  name = "bar"

  rule {
    type    = "forward"
    action  = "ACCEPT"
    comment = "Allow access to HTTP"
    dport   = "80"
    proto   = "tcp"
    log     = "nolog"
  }
}

resource "proxmox_virtual_environment_firewall_rules" "datacenter_firewall" {
  depends_on = [
    proxmox_virtual_environment_cluster_firewall_security_group.foo,
    proxmox_virtual_environment_cluster_firewall_security_group.bar
  ]
  rule {
    type    = "in"
    action  = "ACCEPT"
    comment = "MGMT SSH"
    iface   = "vmbr0"
    macro   = "SSH"
    log     = "nolog"
  }

  rule {
    type    = "in"
    action  = "ACCEPT"
    comment = "MGMT HTTPS"
    iface   = "vmbr0"
    dport   = "8006"
    proto   = "tcp"
    log     = "nolog"
  }

  # rule {
  #   type    = "in"
  #   action  = "ACCEPT"
  #   comment = "MGMT ICMP"
  #   iface   = "vmbr0"
  #   proto   = "icmp"
  #   log     = "nolog"
  # }

  rule {
    security_group = proxmox_virtual_environment_cluster_firewall_security_group.foo.name
    comment        = "foo"
  }
  rule {
    security_group = proxmox_virtual_environment_cluster_firewall_security_group.bar.name
    comment        = "bar"
  }
}
```
2. TF apply

Result:
Image
3. Uncomment the rule in the TF code above
4. TF Plan

```
Terraform will perform the following actions:

  # proxmox_virtual_environment_firewall_rules.datacenter_firewall will be updated in-place
  ~ resource "proxmox_virtual_environment_firewall_rules" "datacenter_firewall" {
        id = "rule-1080330196"

      ~ rule {
          + action         = "ACCEPT"
          ~ comment        = "foo" -> "MGMT ICMP"
          + iface          = "vmbr0"
          + log            = "nolog"
          + proto          = "icmp"
          - security_group = "foo" -> null
          + type           = "in"
            # (2 unchanged attributes hidden)
        }
      ~ rule {
          ~ comment        = "bar" -> "foo"
          ~ security_group = "bar" -> "foo"
            # (2 unchanged attributes hidden)
        }
      + rule {
          + comment        = "bar"
          + enabled        = true
          + security_group = "bar"
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
6. TF apply

Result:Image
As can be seen, rule `#3` with comment `foo` now imports the `bar` security group.

**Expected behavior**
Inserting a rule above security group insertion blocks should not cause the references to break.

**Screenshots**
_See above_

**Additional context**
-

- Clustered Proxmox with nftables host firewall option enabled
- Proxmox version: v9.1.5
- Provider version (ideally it should be the latest version): tested with v0.94.0 and v0.95.0
- Terraform/OpenTofu version: tested with 1.6.6 and 1.14.4
- OS (where you run Terraform/OpenTofu from): macOS
- Debug logs (`TF_LOG=DEBUG terraform apply`): -

### PR DESCRIPTION
**Pull request by xqtc161**
### What does this PR do?

Uses a position aware algorithm to update firewall rules to properly account for shifts when updating firewall rules. Refactors the logic around updating firewall rules to work in 4 phases in order to avoid gaps/lockout at apply-time. The algorithm tracks rules through building rule signatures based on identity fields. Also look at [this comment](https://github.com/bpg/terraform-provider-proxmox/issues/2575#issuecomment-3895874538) in the related issue.

### Contributor's Note

- [x] I have run `make lint` and fixed any issues.
- [ ] I have updated documentation (FWK: schema descriptions + `make docs`; SDK: manual `/docs/` edits). (Not applicable here i believe?)
- [x] I have added / updated acceptance tests (**required** for new resources and bug fixes — see [ADR-006](docs/adr/006-testing-requirements.md)).
- [x] I have considered backward compatibility (no breaking schema changes without `!` in PR title).
- [ ] For new resources: I followed the [reference examples](docs/adr/reference-examples.md).
- [x] I have run `make example` to verify the change works (mainly for SDK / provider config changes).

### Proof of Work

<details>
<summary> make test </summary>

```
go test ./...
?   	github.com/bpg/terraform-provider-proxmox	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/access	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/attribute	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/acme	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/ha	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/hardwaremapping	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/metrics	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/options	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/applier	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/fabric	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/fabric_node	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/subnet	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/vnet	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/cluster/sdn/zone	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/config	[no test files]
ok  	github.com/bpg/terraform-provider-proxmox/fwprovider/nodes	(cached)
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/apt	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/clonedvm	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/datastores	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/firewall	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/network	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/vm	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/vm/cdrom	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/vm/cpu	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/vm/memory	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/vm/rng	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/nodes/vm/vga	[no test files]
ok  	github.com/bpg/terraform-provider-proxmox/fwprovider/pools	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/fwprovider/storage	(cached)
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/test	[no test files]
ok  	github.com/bpg/terraform-provider-proxmox/fwprovider/types	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/fwprovider/types/hardwaremapping	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/fwprovider/types/nodes/apt	(cached)
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/types/stringset	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/fwprovider/validators	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/access	[no test files]
ok  	github.com/bpg/terraform-provider-proxmox/proxmox/api	(cached)
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/acme	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/acme/account	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/acme/plugins	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/firewall	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/ha	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/ha/groups	[no test files]
ok  	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/ha/resources	(cached)
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/mapping	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/metrics	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/sdn	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/sdn/applier	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/sdn/fabric_nodes	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/sdn/fabrics	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/sdn/subnets	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/sdn/vnets	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/cluster/sdn/zones	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/firewall	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/helpers/ptr	[no test files]
ok  	github.com/bpg/terraform-provider-proxmox/proxmox/nodes	(cached)
?   	github.com/bpg/terraform-provider-proxmox/proxmox/nodes/apt	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/nodes/apt/repositories	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/nodes/containers	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/nodes/containers/firewall	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/nodes/firewall	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/nodes/storage	[no test files]
ok  	github.com/bpg/terraform-provider-proxmox/proxmox/nodes/tasks	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmox/nodes/vms	(cached)
?   	github.com/bpg/terraform-provider-proxmox/proxmox/nodes/vms/firewall	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/pools	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmox/ssh	[no test files]
ok  	github.com/bpg/terraform-provider-proxmox/proxmox/storage	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmox/types	(cached)
?   	github.com/bpg/terraform-provider-proxmox/proxmox/types/hardwaremapping	[no test files]
ok  	github.com/bpg/terraform-provider-proxmox/proxmox/types/nodes/apt/repositories	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmox/version	(cached)
?   	github.com/bpg/terraform-provider-proxmox/proxmoxtf	[no test files]
ok  	github.com/bpg/terraform-provider-proxmox/proxmoxtf/datasource	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmoxtf/provider	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/cluster/firewall	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/container	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/firewall	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/pool	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/validators	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm/disk	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm/network	(cached)
?   	github.com/bpg/terraform-provider-proxmox/proxmoxtf/structure	[no test files]
?   	github.com/bpg/terraform-provider-proxmox/proxmoxtf/test	[no test files]
ok  	github.com/bpg/terraform-provider-proxmox/utils	(cached)
ok  	github.com/bpg/terraform-provider-proxmox/utils/ip	(cached)
```

</details>

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #2575

### CODE REVIEW

**Comment by xqtc161** [comment]
I'll add tests on monday and update the PR description then.

**Comment by xqtc161** [comment]
Where should i add new acceptance tests @bpg-dev ? In `proxmoxtf/` or `fwprovider/`? Security groups don't seem to exist in `fwprovider/`... :thinking:

**Comment by bpg-dev** [comment]
@xqtc161 thanks for contributing this!

All acceptance tests live under /fwprovider for historical reasons. There are few SDK resource tests there in /fwprovider/test, including one for firewall resources in [resource_firewall_test.go](https://github.com/bpg/terraform-provider-proxmox/blob/main/fwprovider/test/resource_firewall_test.go)

File: proxmoxtf/resource/firewall/rules.go [hunk 1]
```diff
@@ -492,12 +533,33 @@ func RulesUpdate(ctx context.Context, api firewall.Rule, d *schema.ResourceData)
...
+
 		err := api.UpdateRule(ctx, pos, &ruleBody)
 		if err != nil {
 			diags = append(diags, diag.FromErr(err)...)
 		}
 	}
 
+	var toDelete []int
+
+	for sig, pos := range oldSigToPos {
```
Comment (bpg-dev) [inline proxmoxtf/resource/firewall/rules.go]: at the first glance, should it be `currentPositionMap` rather than `oldSigToPos`, as the rules might have shifted by now?

you probably will be making changes after playing with acceptance tests, so I'll review again in more details after you mark the PR as 'ready'

Comment (bpg-dev) [reply proxmoxtf/resource/firewall/rules.go]: ah, `currentPositionMap` is out of scope here, so perhaps need to refactor this whole thing a bit

Comment (xqtc161) [reply proxmoxtf/resource/firewall/rules.go]: should be fixed. the acceptance tests i started writing also pass with this for now. will push those either today or tomorrow and mark the pr as ready then :D

**Comment by xqtc161** [comment]
I have added acceptance tests which succeed when thrown against a local proxmox node in a VM. Should be good now. lmk if u find any issues! ^^

**Review by bpg-dev — COMMENTED** [review]
Thanks @xqtc161!

I started playing with acceptance test and found a few issues / made a few fixes. Please take a look if that makes sense to you, and that  i didn't break anything. 

- remove unused `oldSigToPos`, rename remaining to `oldBySig`
- better error handling: do now swallow missing rule if e.g. API error
- delete positions in reverse order, for simplicity
- scope old standalone rules to VM so they don't collide
- add more integration tests

Overall, LGTM! 🚀

**Comment by xqtc161** [comment]
Your changes look good to me. Good catches! :) 

This was the first time I've ever written Go besides a hello world and golings and I really enjoyed working on this, so thanks for always responding this quickly :>

**Comment by xqtc161** [comment]
Huh i just realized that for some reason my commit signatures are gone... Would you mind if I signed them and force push so u can rebase your commit on top of my signed commits?

**Comment by bpg-dev** [comment]
Sure, go ahead

**Comment by bpg-dev** [comment]
@all-contributors please add @xqtc161 for code
