### PR TITLE
fix(provider): Deprecate `virtual_environment` block

### LINKED ISSUE #117: CDKTF doesn't extract provider values
**Describe the bug**
When using CDKTF (v.0.12.1) and configuring the provider, I cannot add a "virtual_environment {}" block. An error "Argument of type virtualEnvironment is not assignable to parameter of type 'ProxmoxProviderConfig'". CDKTF only recognizes the "alias" parameter. Without the parameter, deployment seems to fail on this:

```
│ Error: you must specify the virtual environment details in the provider configuration
│ 
│   with proxmox_virtual_environment_pool.resource-pool,
│   on cdk.tf.json line 37, in resource.proxmox_virtual_environment_pool.resource-pool:
│   37:       }
```

**To Reproduce**
In a cdktf project, create a proxmox resource and declare the provider:
```nodejs
    // Setup provider
    new ProxmoxProvider(this, 'proxmox', {});
```
run cdktf deploy

**Expected behavior**
The provider should be generated correctly

**Additional context**
None at this point

### PR DESCRIPTION
**Pull request by kugo12**
Also deprecate virtual_environment block, update docs and examples.
Not sure if there is any reason for keeping it.

Fixes #117 
Apparently CDKTF skips schemas without attributes, it has been fixed but it is available only in prerelease currently (https://github.com/hashicorp/terraform-cdk/pull/2736)

### Contributor's Note
Please mark the following items with an [x] if they apply to your PR.
Leave the [ ] if they are not applicable, or if you have not completed the item.
- [x] I have added / updated documentation in `/docs` for any user-facing features or additions.
- [x] I have added / updated templates in `/examples` for any new or updated resources / data sources.
  - [x] I have ran `make examples` to verify that the change works as expected. 

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #117

### CODE REVIEW

File: proxmoxtf/provider/schema.go [hunk 1]
```diff
@@ -7,123 +7,96 @@
...
+			Description: "The password for the Proxmox Virtual Environment API",
+			DefaultFunc: schema.MultiEnvDefaultFunc(
+				[]string{"PROXMOX_VE_PASSWORD", "PM_VE_PASSWORD"},
+				nil,
+			),
+			AtLeastOneOf: []string{
+				mkProviderPassword,
+				fmt.Sprintf("%s.0.%s", mkProviderVirtualEnvironment, mkProviderPassword),
+			},
+			ValidateFunc: validation.StringIsNotEmpty,
```
Comment (bpg-dev) [inline proxmoxtf/provider/schema.go:85]: nice! thanks for cleaning up those validators 👍🏼

**Review by bpg — APPROVED** [review]
Looks good, thanks @kugo12!
